# Generated by Django 4.2.6 on 2024-03-29 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Catalogz", max_length=200)),
                (
                    "desc",
                    models.TextField(
                        default="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="opeoluwafatunmbi@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+2348155260863", max_length=20)),
                (
                    "address",
                    models.CharField(default="25, Lagos, Nigeria", max_length=500),
                ),
                (
                    "work_hours",
                    models.CharField(default="09:00 - 17:00", max_length=500),
                ),
                (
                    "maps_url",
                    models.URLField(
                        default="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                    ),
                ),
                (
                    "site",
                    models.URLField(
                        default="https://www.catalogz.com/", verbose_name="Company Site"
                    ),
                ),
                (
                    "fb",
                    models.URLField(
                        default="https://www.facebook.com", verbose_name="Facebook"
                    ),
                ),
                (
                    "ig",
                    models.URLField(
                        default="https://www.instagram.com/", verbose_name="Instagram"
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://www.twitter.com/", verbose_name="Twitter"
                    ),
                ),
                (
                    "ln",
                    models.URLField(
                        default="https://www.linkedin.com/", verbose_name="Linkedin"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Chief Executive Officer", "Chief Executive Officer"),
                            ("Chief Marketing Officer", "Chief Marketing Officer"),
                            ("Accounting Executive", "Accounting Executive"),
                        ],
                        max_length=200,
                    ),
                ),
                ("desc", models.CharField(max_length=300)),
                ("avatar", models.ImageField(upload_to="team/")),
                (
                    "fb",
                    models.URLField(
                        default="https://www.facebook.com", verbose_name="Facebook"
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://www.twitter.com/", verbose_name="Twitter"
                    ),
                ),
                (
                    "ln",
                    models.URLField(
                        default="https://www.linkedin.com/", verbose_name="Linkedin"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
