# Generated by Django 4.2.6 on 2024-03-29 22:36

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("desc", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(default="fallback.jpg", upload_to="gallery/"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMG", "Image"), ("VID", "Video")],
                        default="IMG",
                        max_length=3,
                    ),
                ),
                ("dimensions", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("JPEG", "JPEG"), ("PNG", "PNG"), ("MP4", "MP4")],
                        default="JPEG",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
